### ISSUE TITLE
download of version v0.13.0 fails on linux64

### ISSUE THREAD

**Issue by vicolachips44** [mllrsohn/node-webkit-builder#222]
When running command nwbuild the script tries to download version v0.13.0 from http://dl.nwjs.io/v0.13.0 but fails since there is no version available. I mean yes there is one in fact but it's path is:
http://dl.nwjs.io/v0.13.0/alpha0/.
nwbuild will also fail to start if there is no network connection.

**Comment by arthurmichel** [comment]
Hey!
add the version
if you are using GulpJS ex.

var nw = new NwBuilder({
        version: '0.12.1',
        files: [ './**'],
        platforms: ['osx'] // change this to 'win' for/on windows
    });

**Comment by vicolachips44** [comment]
Thanks for the tip!

Actually I'm using the nwbuild command under linux so i run: nwbuild -r src/

src folder being my source folder :)

Maybe there is a way to set this parameter with the command line tool ?

**Comment by arthurmichel** [comment]
nwbuild -v v0.12.1 src/

**Comment by vicolachips44** [comment]
It works like a charm, thanks!

2015-05-11 11:52 GMT+02:00 Arthur Michel <notifications@github.com>:

**Comment by kasongoyo** [comment]
Thanks so much arthurmichel,

**Comment by adam-lynch** [comment]
From https://github.com/mllrsohn/node-webkit-builder/issues/226#issue-77560188:

>When running nwb (as part of phonegap-app-desktop build), it dies with "Fatal error: Unable to download nodewebkit." After some debugging, the error being thrown is from request, and is "Invalid protocol: undefined", in the downloader. This is because lib/downloader.js line 50 sets rq.proxy = true, but the request docs show that request.proxy should be set to a proxy URL, not a boolean. I commented out rq.proxy=true and that made everything work, but haven't sent a pull request removing the line because I imagine you set proxy=true for some reason and so this needs thinking through.

**Comment by adam-lynch** [comment]
Ignore last comment. I've published 1.0.12 which fixes this. It now validates the latest version (i.e. checks that it's not an alpha build).

**Comment by estvmachine** [comment]
How can i install a certain version not the latest, i want specifically the '**node-webkit-v0.8.6-win-ia32'** version. In advanced, thanks for you hard work!.

**Comment by adam-lynch** [comment]
Pass `version: '0.8.6'`

**Comment by adam-lynch** [comment]
Sorry, submitted that early. Either put `version: '0.8.6'` in options object passed to node-webkit-builder (if you're using it programmatically) or use `-v 0.8.6` if you're using the command-line

**Comment by damiandennis** [comment]
running version 1.0.12 but still having issue with this.

if I run:

```
nwbuild -p linux64 ./
```

I get:

Downloading: http://dl.nwjs.io/v0.13.0/nwjs-v0.13.0-linux-x64.tar.gz
ERROR: The version 0.13.0 does not have a corresponding build posted at http://dl.node-webkit.org/.

If i run 

```
nwbuild -p linux64 -v 0.12.1 ./
```

it works.

**Comment by damiandennis** [comment]
The workaround works but does not make sense to have the default throw an error due to alpha status.

**Comment by fritx** [comment]
for me, added `-p osx` flag and it worked :+1:

**Comment by estvmachine** [comment]
@adam-lynch  works for me, thanks
